spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&sslMode=DISABLED
    username: root
    password: michaelTMAC1314
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.cyn: debug
  file: log/blog-dev.log
server:
  port: 8081